function [spars] = whiffletree4(magnitude,location)
matrix = [0,0,0,0,1,1;...
          0,0,1,1,0,0;...
          0,0,0,0,magnitude(3),-magnitude(4);...
          0,0,magnitude(1),-magnitude(2),0,0;...
          (magnitude(1)+magnitude(2)),-(magnitude(3)+magnitude(4)),0,0,0,0;...
          1,1,0,-1,-1,0];
b = [location(4)-location(3);...
         location(2)-location(1);...
         0;...
         0;...
         0;...
         location(3)-location(2)];
spars = inv(matrix)*b;
end